from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any

from bot_api.services.liga_entrega_import_service import LigaEntregaReportImportService
from bot_api.services.liga_entrega_report_store import LigaEntregaReportStore


ADMIN_IMPORT_CRITICA_PIPELINE_DATASETS = {"critica_rn", "dclientes", "doperacoes", "dprecos", "dsetores", "dcondicoes"}


def build_admin_import_datasets(
    *,
    project_root: Path,
    services: Any,
    filial_labels: dict[str, str],
    liga_entrega_report_store: LigaEntregaReportStore | None = None,
) -> dict[str, dict[str, Any]]:
    entrega_reports_root = Path(r"M:/REVENDA") / f"SDPO {date.today().year}" / "DPO" / "PILAR ENTREGA" / "RELATORIOS"
    datasets: dict[str, dict[str, Any]] = {
        "dsetores": {
            "label": "dSetores",
            "default_path": project_root / "data" / "dSetores" / "dSetores.csv",
            "service": services.dsetores_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_csv",
            "summarize_method": "summarize_csv",
            "import_method": "import_csv",
        },
        "dprecos": {
            "label": "DPrecos",
            "default_path": project_root / "data" / "dPrecos" / "DPrecos.xlsx",
            "service": services.dprecos_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "doperacoes": {
            "label": "dOperacoes",
            "default_path": project_root / "data" / "dOperacoes" / "dOperacoes.csv",
            "service": services.doperacoes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "drevendas": {
            "label": "dRevendas",
            "default_path": project_root / "data" / "dRevendas" / "dRevendas.xlsx",
            "allow_default_source": False,
            "service": services.drevendas_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dcondicoes": {
            "label": "dCondicoes",
            "default_path": project_root / "data" / "dCondicoes" / "dCondicoes.csv",
            "allow_default_source": False,
            "service": services.dcondicoes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dprodutos": {
            "label": "dProdutos",
            "default_path": project_root / "data" / "dProdutos" / "01.11.CSV",
            "allow_default_source": False,
            "service": services.dprodutos_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dgarrafeiras": {
            "label": "Tabela de Garrafeiras - 0109",
            "default_path": project_root / "data" / "dGarrafeiras" / "0109.csv",
            "allow_default_source": False,
            "service": services.dgarrafeiras_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "produto_cestas": {
            "label": "Cesta de Produtos",
            "default_path": project_root / "data" / "dProdutos" / "Cesta de Produtos.xlsx",
            "allow_default_source": False,
            "service": services.produto_cestas_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dmateriais": {
            "label": "Tabela de Materiais - 0112",
            "default_path": project_root / "data" / "dMateriais" / "0112.csv",
            "allow_default_source": False,
            "service": services.dmateriais_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        **{
            f"boletos_bradesco_op_{filial_code}": {
                "label": f"Boletos Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Boletos" / f"boletos_bradesco_operacao_{filial_code}.pdf",
                "allow_default_source": False,
                "service": services.boletos_pdf_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".pdf",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        **{
            f"estoque_020304_op_{filial_code}": {
                "label": f"Estoque 020304 Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Estoque" / f"020304_operacao_{filial_code}.csv",
                "allow_default_source": False,
                "service": services.estoque_020304_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".csv",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        **{
            f"relatorio_031120_op_{filial_code}": {
                "label": f"Relatorio 031120 Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Relatorio031120" / f"031120_operacao_{filial_code}.csv",
                "allow_default_source": False,
                "service": services.relatorio_031120_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".csv",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        "relatorio_03114902_geo": {
            "label": "Relatorio 03114902 - Todas as operacoes",
            "default_path": project_root / "data" / "Relatorio03114902" / "03114902.csv",
            "allow_default_source": False,
            "service": services.relatorio_03114902_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dclientes": {
            "label": "dClientes",
            "default_path": project_root / "data" / "dClientes" / "dClientes.csv",
            "service": services.dclientes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_csv",
            "summarize_method": "summarize_csv",
            "import_method": "import_csv",
        },
        "inadimplencia": {
            "label": "Inadimplencia",
            "default_path": project_root / "data" / "Inadimplencia",
            "allow_default_source": False,
            "service": services.inadimplencia_import_service,
            "upload_mode": "multiple",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "comodatos": {
            "label": "Comodatos",
            "default_path": project_root / "data" / "Comodatos",
            "service": services.comodatos_import_service,
            "upload_mode": "multiple",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "giro": {
            "label": "Giro de Vasilhame",
            "default_path": project_root / "data" / "Giro" / "giro.xlsx",
            "service": services.giro_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.xls",
            "validate_method": "validate_workbook",
            "summarize_method": "summarize_workbook",
            "import_method": "import_workbook",
        },
        **{
            f"critica_op_{filial_code}": {
                "label": f"Critica Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Critica" / f"critica_operacao_{filial_code}.csv",
                "allow_default_source": False,
                "service": services.critica_operacao_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".csv",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        "critica_rn": {
            "label": "Critica RN",
            "default_path": project_root / "data" / "CriticaRN" / "critica_rn.xlsx",
            "allow_default_source": False,
            "service": services.critica_rn_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "documentacao_pendente": {
            "label": "Documentacao Pendente",
            "default_path": project_root / "data" / "DocumentacaoPendente" / "documentacao_pendente.csv",
            "service": services.documentacao_pendente_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "prazo_limite": {
            "label": "Prazo e Limite",
            "default_path": project_root / "data" / "PrazoLimite" / "prazo_limite.xlsx",
            "service": services.prazo_limite_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.xls,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
    }

    if liga_entrega_report_store is not None:
        liga_specs = {
            "liga_030805": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.08.05 Rotas do dia",
                "routine": "030805_LIGA",
                "folder": entrega_reports_root / "03.08.05",
                "upload_mode": "multiple",
                "accept_extensions": ".csv,.txt",
                "patterns": (r"^(PATOS|SUME)_\d{2}_\d{2}\.csv$", r"^2artd\d{2}_\d{4}\.txt$"),
                "max_file_count": 120,
                "history_by_filename_date": True,
            },
            "liga_031120": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.11.20 Portaria",
                "routine": "031120_BOT",
                "folder": entrega_reports_root / "03.11.20",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.11\.20_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_030224_motorista": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.02.24 Devolucoes Motorista",
                "routine": "030224_MOTORISTA_LIGA",
                "folder": entrega_reports_root / "03.02.24" / "Motorista",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.02\.24_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_030224_resumo": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.02.24 Resumo",
                "routine": "030224_RESUMO_LIGA",
                "folder": entrega_reports_root / "03.02.24" / "Resumo",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.02\.24_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_030224_ajudante": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.02.24 Devolucoes Ajudante",
                "routine": "030224_AJUDANTE_LIGA",
                "folder": entrega_reports_root / "03.02.24" / "Ajudante",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.02\.24_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_030237": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.02.37 Entregas",
                "routine": "030237",
                "folder": entrega_reports_root / "03.02.37 - Entregas",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.02\.37_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_03114902": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.11.49.02 Cidades por mapa",
                "routine": "03114902_BOT",
                "folder": entrega_reports_root / "03.11.49.02",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.11\.49\.02_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_031129": {
                "allow_default_source": False,
                "label": "Liga Entrega - 03.11.29 Equipes do dia",
                "routine": "031129_LIGA",
                "folder": entrega_reports_root / "03.11.29",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^03\.11\.29_(PATOS|SUME)_[A-Z]{3}\.csv$",),
            },
            "liga_espelho_ponto": {
                "allow_default_source": True,
                "label": "Liga Entrega - Espelho de ponto",
                "routine": "PONTOMAIS_ESPELHO",
                "folder": entrega_reports_root / "PONTOMAIS" / "espelho_matricula",
                "upload_mode": "multiple",
                "accept_extensions": ".csv",
                "patterns": (r"^Espelho_[A-Z]{3}_(PATOS|SUME)_?\.csv$",),
            },
            "liga_checklist_frota": {
                "allow_default_source": True,
                "label": "Liga Entrega - Checklist Frota",
                "routine": "CHECKLIST_FROTA",
                "folder": entrega_reports_root / "Checklist Frota" / "Checklist Setembro.xlsx",
                "upload_mode": "single",
                "accept_extensions": ".xlsx,.xlsm",
                "patterns": (r"^Checklist .*\.xls[xm]$",),
            },
        }
        for dataset_name, spec in liga_specs.items():
            datasets[dataset_name] = {
                "label": spec["label"],
                "default_path": spec["folder"],
                "allow_default_source": bool(spec.get("allow_default_source", False)),
                "service": LigaEntregaReportImportService(
                    report_store=liga_entrega_report_store,
                    dataset_name=dataset_name,
                    label=spec["label"],
                    routine=spec["routine"],
                    allowed_extensions={item.strip() for item in str(spec["accept_extensions"]).split(",") if item.strip()},
                    expected_name_patterns=tuple(spec["patterns"]),
                    history_by_filename_date=bool(spec.get("history_by_filename_date", False)),
                ),
                "upload_mode": spec["upload_mode"],
                "accept_extensions": spec["accept_extensions"],
                "max_file_count": spec.get("max_file_count"),
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }

    return datasets
