from __future__ import annotations

from pathlib import Path
from typing import Any


ADMIN_IMPORT_CRITICA_PIPELINE_DATASETS = {"critica_rn", "dclientes", "doperacoes", "dprecos", "dsetores", "dcondicoes"}


def build_admin_import_datasets(
    *,
    project_root: Path,
    services: Any,
    filial_labels: dict[str, str],
) -> dict[str, dict[str, Any]]:
    return {
        "dsetores": {
            "label": "dSetores",
            "default_path": project_root / "data" / "dSetores" / "dSetores.csv",
            "service": services.dsetores_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_csv",
            "summarize_method": "summarize_csv",
            "import_method": "import_csv",
        },
        "dprecos": {
            "label": "DPrecos",
            "default_path": project_root / "data" / "dPrecos" / "DPrecos.xlsx",
            "service": services.dprecos_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "doperacoes": {
            "label": "dOperacoes",
            "default_path": project_root / "data" / "dOperacoes" / "dOperacoes.csv",
            "service": services.doperacoes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "drevendas": {
            "label": "dRevendas",
            "default_path": project_root / "data" / "dRevendas" / "dRevendas.xlsx",
            "allow_default_source": False,
            "service": services.drevendas_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dcondicoes": {
            "label": "dCondicoes",
            "default_path": project_root / "data" / "dCondicoes" / "dCondicoes.csv",
            "allow_default_source": False,
            "service": services.dcondicoes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "dprodutos": {
            "label": "dProdutos",
            "default_path": project_root / "data" / "dProdutos" / "01.11.CSV",
            "allow_default_source": False,
            "service": services.dprodutos_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "produto_cestas": {
            "label": "Cesta de Produtos",
            "default_path": project_root / "data" / "dProdutos" / "Cesta de Produtos.xlsx",
            "allow_default_source": False,
            "service": services.produto_cestas_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        **{
            f"boletos_bradesco_op_{filial_code}": {
                "label": f"Boletos Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Boletos" / f"boletos_bradesco_operacao_{filial_code}.pdf",
                "allow_default_source": False,
                "service": services.boletos_pdf_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".pdf",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        "dclientes": {
            "label": "dClientes",
            "default_path": project_root / "data" / "dClientes" / "dClientes.csv",
            "service": services.dclientes_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_csv",
            "summarize_method": "summarize_csv",
            "import_method": "import_csv",
        },
        "inadimplencia": {
            "label": "Inadimplencia",
            "default_path": project_root / "data" / "Inadimplencia",
            "allow_default_source": False,
            "service": services.inadimplencia_import_service,
            "upload_mode": "multiple",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "comodatos": {
            "label": "Comodatos",
            "default_path": project_root / "data" / "Comodatos",
            "service": services.comodatos_import_service,
            "upload_mode": "multiple",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "giro": {
            "label": "Giro de Vasilhame",
            "default_path": project_root / "data" / "Giro" / "giro.xlsx",
            "service": services.giro_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.xls",
            "validate_method": "validate_workbook",
            "summarize_method": "summarize_workbook",
            "import_method": "import_workbook",
        },
        **{
            f"critica_op_{filial_code}": {
                "label": f"Critica Operacao {filial_code} - {filial_labels[filial_code]}",
                "default_path": project_root / "data" / "Critica" / f"critica_operacao_{filial_code}.csv",
                "allow_default_source": False,
                "service": services.critica_operacao_import_services[filial_code],
                "upload_mode": "single",
                "accept_extensions": ".csv",
                "validate_method": "validate_source",
                "summarize_method": "summarize_source",
                "import_method": "import_source",
            }
            for filial_code in sorted(filial_labels, key=int)
        },
        "critica_rn": {
            "label": "Critica RN",
            "default_path": project_root / "data" / "CriticaRN" / "critica_rn.xlsx",
            "allow_default_source": False,
            "service": services.critica_rn_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "documentacao_pendente": {
            "label": "Documentacao Pendente",
            "default_path": project_root / "data" / "DocumentacaoPendente" / "documentacao_pendente.csv",
            "service": services.documentacao_pendente_import_service,
            "upload_mode": "single",
            "accept_extensions": ".csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
        "prazo_limite": {
            "label": "Prazo e Limite",
            "default_path": project_root / "data" / "PrazoLimite" / "prazo_limite.xlsx",
            "service": services.prazo_limite_import_service,
            "upload_mode": "single",
            "accept_extensions": ".xlsx,.xlsm,.xls,.csv",
            "validate_method": "validate_source",
            "summarize_method": "summarize_source",
            "import_method": "import_source",
        },
    }
