from __future__ import annotations

# Tabela operacional Motivos Devolucao.xlsx, usada para classificar as devolucoes da Liga.
MOTIVOS_DEVOLUCAO: dict[str, dict[str, str]] = {'1': {'motivo': 'FALTA CAMINHAO PARA CARREGAR', 'responsabilidade': 'LOGISTICA'},
 '2': {'motivo': 'Sem Vasilhame Ambev', 'responsabilidade': 'VENDAS'},
 '3': {'motivo': 'Devolucao NFe', 'responsabilidade': 'VENDAS'},
 '4': {'motivo': 'Devolucao NFe', 'responsabilidade': 'PROJETO NFE'},
 '5': {'motivo': 'Canc.Por Prazo Expirado SEFAZ', 'responsabilidade': 'PROJETO NFE'},
 '6': {'motivo': 'Canc. Aut. NF Ret. Vasilhame', 'responsabilidade': 'PROJETO NFE'},
 '7': {'motivo': 'OUTROS MOTIVOS VALIDADO AC', 'responsabilidade': 'PROCESSO'},
 '8': {'motivo': 'Mapa nao carregado / nao canc.', 'responsabilidade': 'PROCESSO'},
 '9': {'motivo': 'Pronta entrega / Pamonha', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '10': {'motivo': 'Caminhao assaltado', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '11': {'motivo': 'RISCO EXTERNO', 'responsabilidade': 'LOGISTICA'},
 '12': {'motivo': '(C)Ind. Frota / Cam. Quebrado', 'responsabilidade': 'LOGISTICA'},
 '13': {'motivo': '(C)Absenteismo Equipe Entrega', 'responsabilidade': 'LOGISTICA'},
 '14': {'motivo': '(C)Ind. Freteiro', 'responsabilidade': 'LOGISTICA'},
 '15': {'motivo': '(C)Ind. Frota / Greves', 'responsabilidade': 'LOGISTICA'},
 '16': {'motivo': '(C)Ind. Frota / Excesso Volume', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '17': {'motivo': '(C)Excesso de peso', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '18': {'motivo': '(C)Produtiv. / baixa ocupacao', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '19': {'motivo': '(C)Produtiv. / roterizacao', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '20': {'motivo': '(C)Horario 2a. Viagem', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '21': {'motivo': '(C)Capacidade armazem', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '22': {'motivo': '(C)Solicitacao vendas/cliente', 'responsabilidade': 'VENDAS'},
 '23': {'motivo': '(C)Pedidos duplicados', 'responsabilidade': 'VENDAS'},
 '24': {'motivo': '(C)Riscos externos', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '25': {'motivo': '(C)Falta produto p/ carreg.', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '26': {'motivo': '(C)Furo Cliente Retira', 'responsabilidade': 'MERCADO'},
 '27': {'motivo': '(C)Problemas Sistema Ambev', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '28': {'motivo': '(C)Problemas CTE', 'responsabilidade': 'LOGISTICA'},
 '33': {'motivo': 'Nao Fez Pedido', 'responsabilidade': 'VENDAS'},
 '34': {'motivo': 'Pedido Duplicado', 'responsabilidade': 'VENDAS'},
 '37': {'motivo': 'PDV FECHADO (HORARIO COM.)', 'responsabilidade': 'MERCADO'},
 '38': {'motivo': 'SEM DINHEIRO/CHEQUE', 'responsabilidade': 'MERCADO'},
 '39': {'motivo': 'CLIENTE CANCELOU', 'responsabilidade': 'MERCADO'},
 '41': {'motivo': 'SEM VASILHAME', 'responsabilidade': 'VENDAS'},
 '42': {'motivo': 'Produto/Quantidade Errada', 'responsabilidade': 'VENDAS'},
 '45': {'motivo': 'TEMPO INSUFICIENTE', 'responsabilidade': 'LOGISTICA'},
 '46': {'motivo': 'Endereco Nao Encontrado', 'responsabilidade': 'LOGISTICA'},
 '48': {'motivo': 'PDV FECHADO APOS HORARIO', 'responsabilidade': 'LOGISTICA'},
 '50': {'motivo': 'CARGA ERRADA ARMAZEM', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '51': {'motivo': 'NF ERRADA', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '52': {'motivo': 'FALTA PRODUTO ESTOQUE', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '53': {'motivo': 'PROD PROXIMO VENCIM. COMERCIAL', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '54': {'motivo': 'IMPOSSIBILIDADE CARREGAMENTO', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '55': {'motivo': 'QUALIDADE DO PRODUTO', 'responsabilidade': 'FINANCEIRO / ARMAZEM'},
 '60': {'motivo': 'PRECO ERRADO', 'responsabilidade': 'VENDAS'},
 '61': {'motivo': 'PRAZO ERRADO', 'responsabilidade': 'VENDAS'},
 '62': {'motivo': 'FORMA PAGAMENTO ERRADA', 'responsabilidade': 'VENDAS'},
 '63': {'motivo': 'PRODUTO / QTDE. ERRADA', 'responsabilidade': 'VENDAS'},
 '64': {'motivo': 'SEM VASILHAME', 'responsabilidade': 'VENDAS'},
 '65': {'motivo': 'NAO FEZ PEDIDO', 'responsabilidade': 'VENDAS'},
 '66': {'motivo': 'CHEQUE TERCEIRO / FALTA ENDOSS', 'responsabilidade': 'VENDAS'},
 '67': {'motivo': 'ESTOQUE CHEIO', 'responsabilidade': 'VENDAS'},
 '68': {'motivo': 'TROCA (SEM SELO / QTDE. ERRADA', 'responsabilidade': 'VENDAS'},
 '69': {'motivo': 'PRE-FATURAMENTO', 'responsabilidade': 'VENDAS'},
 '70': {'motivo': 'CLIENTE CANCELOU', 'responsabilidade': 'MERCADO'},
 '71': {'motivo': 'SEM DINHEIRO/CHEQUE', 'responsabilidade': 'MERCADO'},
 '72': {'motivo': 'PDV FECHADO (HORARIO COM.)', 'responsabilidade': 'MERCADO'},
 '73': {'motivo': 'FALTA DE ATIVOS DE GIRO', 'responsabilidade': 'MERCADO'},
 '74': {'motivo': 'LOCAL ARMAZENAGEM INADEQUADO', 'responsabilidade': 'MERCADO'},
 '77': {'motivo': 'DEVOLUÇÃO NF-E', 'responsabilidade': 'MERCADO'},
 '80': {'motivo': 'CAMINHAO QUEBRADO / ACIDENTE', 'responsabilidade': 'LOGISTICA'},
 '81': {'motivo': 'PRODUTO DANIFICADO / FALTA', 'responsabilidade': 'LOGISTICA'},
 '82': {'motivo': 'ENDERECO NAO ENCONTRADO', 'responsabilidade': 'LOGISTICA'},
 '83': {'motivo': 'PROPRIETARIO AUSENTE', 'responsabilidade': 'LOGISTICA'},
 '84': {'motivo': 'AREA DE RISCO', 'responsabilidade': 'LOGISTICA'},
 '85': {'motivo': 'DIFICIL ACESSO', 'responsabilidade': 'LOGISTICA'},
 '86': {'motivo': 'HORARIO DE ENTREGA', 'responsabilidade': 'LOGISTICA'},
 '87': {'motivo': 'TEMPO INSUFICIENTE', 'responsabilidade': 'LOGISTICA'},
 '88': {'motivo': 'REFUGO DE VASILHAME', 'responsabilidade': 'LOGISTICA'},
 '89': {'motivo': 'PDV FECHADO APOS HORARIO', 'responsabilidade': 'LOGISTICA'},
 '90': {'motivo': 'PRONTA ENTREGA', 'responsabilidade': 'PROCESSO'},
 '91': {'motivo': 'CONSIGNACAO', 'responsabilidade': 'PROCESSO'},
 '92': {'motivo': 'CAMINHAO ASSALTADO', 'responsabilidade': 'PROCESSO'},
 '93': {'motivo': 'DEVOLUCAO DE COMODATO', 'responsabilidade': 'PROCESSO'},
 '94': {'motivo': 'TROCA REALIZADA', 'responsabilidade': 'PROCESSO'},
 '95': {'motivo': 'TROCA P/ INVERSAO', 'responsabilidade': 'PROCESSO'},
 '57': {'motivo': 'Produto Danificado', 'responsabilidade': 'LOGISTICA'}}
