#!/bin/sh
set -eu

if [ -z "${BOT_DATABASE_USER:-}" ] || [ -z "${BOT_DATABASE_PASSWORD:-}" ]; then
  echo "BOT_DATABASE_USER/BOT_DATABASE_PASSWORD nao configurados; pulando criacao do role de acesso do bot."
  exit 0
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${BOT_DATABASE_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${BOT_DATABASE_USER}', '${BOT_DATABASE_PASSWORD}');
  ELSE
    EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', '${BOT_DATABASE_USER}', '${BOT_DATABASE_PASSWORD}');
  END IF;
END
\$\$;

CREATE SCHEMA IF NOT EXISTS bot_access AUTHORIZATION ${POSTGRES_USER};
CREATE SCHEMA IF NOT EXISTS reports AUTHORIZATION ${POSTGRES_USER};
ALTER SCHEMA bot_access OWNER TO ${POSTGRES_USER};
ALTER SCHEMA reports OWNER TO ${POSTGRES_USER};

DO \$\$
DECLARE
  object_record RECORD;
BEGIN
  FOR object_record IN
    SELECT n.nspname AS schema_name, c.relname AS object_name, c.relkind
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN ('bot_access', 'reports')
      AND c.relkind IN ('r', 'v', 'm')
  LOOP
    IF object_record.relkind = 'r' THEN
      EXECUTE format('ALTER TABLE %I.%I OWNER TO ${POSTGRES_USER}', object_record.schema_name, object_record.object_name);
    ELSIF object_record.relkind = 'v' THEN
      EXECUTE format('ALTER VIEW %I.%I OWNER TO ${POSTGRES_USER}', object_record.schema_name, object_record.object_name);
    ELSIF object_record.relkind = 'm' THEN
      EXECUTE format('ALTER MATERIALIZED VIEW %I.%I OWNER TO ${POSTGRES_USER}', object_record.schema_name, object_record.object_name);
    END IF;
  END LOOP;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${BOT_DATABASE_USER};
GRANT USAGE ON SCHEMA bot_access TO ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA bot_access FROM ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot_access FROM ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA bot_access FROM ${BOT_DATABASE_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA bot_access TO ${BOT_DATABASE_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bot_access TO ${BOT_DATABASE_USER};

REVOKE ALL ON SCHEMA reports FROM ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA reports FROM ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA reports FROM ${BOT_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA reports FROM ${BOT_DATABASE_USER};
REVOKE CREATE ON SCHEMA bot_access FROM ${BOT_DATABASE_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA bot_access
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${BOT_DATABASE_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA bot_access
  GRANT USAGE, SELECT ON SEQUENCES TO ${BOT_DATABASE_USER};
EOSQL

if [ -n "${BOT_REPORTS_DATABASE_USER:-}" ] && [ -n "${BOT_REPORTS_DATABASE_PASSWORD:-}" ]; then
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${BOT_REPORTS_DATABASE_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${BOT_REPORTS_DATABASE_USER}', '${BOT_REPORTS_DATABASE_PASSWORD}');
  ELSE
    EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', '${BOT_REPORTS_DATABASE_USER}', '${BOT_REPORTS_DATABASE_PASSWORD}');
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${BOT_REPORTS_DATABASE_USER};
GRANT USAGE ON SCHEMA reports TO ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA reports FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA reports FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA reports FROM ${BOT_REPORTS_DATABASE_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA reports TO ${BOT_REPORTS_DATABASE_USER};

REVOKE ALL ON SCHEMA bot_access FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA bot_access FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot_access FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA bot_access FROM ${BOT_REPORTS_DATABASE_USER};
REVOKE CREATE ON SCHEMA reports FROM ${BOT_REPORTS_DATABASE_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA reports
  GRANT SELECT ON TABLES TO ${BOT_REPORTS_DATABASE_USER};
EOSQL

fi
